"""allow_null_user_id_in_detections

Revision ID: 265fc34c8c24
Revises: f27b9d42ef15
Create Date: 2025-08-27 09:23:32.605080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265fc34c8c24'
down_revision: Union[str, Sequence[str], None] = 'f27b9d42ef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
