"""Create users table with proper base

Revision ID: 2ea6f87380b9
Revises: fb48d7b587ad
Create Date: 2025-08-17 23:42:15.192747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea6f87380b9'
down_revision: Union[str, Sequence[str], None] = 'fb48d7b587ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('openid', sa.String(length=64), nullable=True, comment='微信OpenID'),
    sa.Column('unionid', sa.String(length=64), nullable=True, comment='微信UnionID'),
    sa.Column('session_key', sa.String(length=64), nullable=True, comment='微信会话密钥'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='用户昵称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='性别：0-未知，1-男，2-女'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
    sa.Column('province', sa.String(length=50), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('language', sa.String(length=20), nullable=True, comment='语言'),
    sa.Column('role', sa.Enum('USER', 'VOLUNTEER', 'ADMIN', name='userrole'), nullable=True, comment='用户角色'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=True, comment='用户状态'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('height', sa.Integer(), nullable=True, comment='身高(cm)'),
    sa.Column('weight', sa.Integer(), nullable=True, comment='体重(kg)'),
    sa.Column('health_conditions', sa.Text(), nullable=True, comment='健康状况描述'),
    sa.Column('dietary_preferences', sa.Text(), nullable=True, comment='饮食偏好'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='过敏信息'),
    sa.Column('scan_count', sa.Integer(), nullable=True, comment='扫描次数'),
    sa.Column('last_scan_time', sa.DateTime(), nullable=True, comment='最后扫描时间'),
    sa.Column('total_reports', sa.Integer(), nullable=True, comment='生成报告总数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True, comment='是否启用通知'),
    sa.Column('privacy_agreement', sa.Boolean(), nullable=True, comment='是否同意隐私协议'),
    sa.Column('terms_agreement', sa.Boolean(), nullable=True, comment='是否同意使用条款'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
