"""Create detections table with proper constraints

Revision ID: 712c39112b0c
Revises: 2ea6f87380b9
Create Date: 2025-08-19 19:03:22.688242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712c39112b0c'
down_revision: Union[str, Sequence[str], None] = '2ea6f87380b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='用户ID（匿名用户时为空）',
               existing_comment='用户ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='用户ID',
               existing_comment='用户ID（匿名用户时为空）')
    # ### end Alembic commands ###
