"""fix_reports_table_with_correct_base

Revision ID: f27b9d42ef15
Revises: 3b52efe11b80
Create Date: 2025-08-27 08:43:21.098736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27b9d42ef15'
down_revision: Union[str, Sequence[str], None] = '3b52efe11b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False, comment='报告ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', 'SINGLE', name='reporttype'), nullable=False, comment='报告类型'),
    sa.Column('status', sa.Enum('GENERATING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='reportstatus'), nullable=True, comment='报告状态'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='报告标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='报告描述'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='统计开始时间'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='统计结束时间'),
    sa.Column('total_scans', sa.Integer(), nullable=True, comment='总扫描次数'),
    sa.Column('total_products', sa.Integer(), nullable=True, comment='总产品数量'),
    sa.Column('detection_ids', sa.JSON(), nullable=True, comment='包含的检测记录ID列表'),
    sa.Column('avg_energy_kcal', sa.Float(), nullable=True, comment='平均能量摄入(kcal)'),
    sa.Column('avg_protein', sa.Float(), nullable=True, comment='平均蛋白质摄入(g)'),
    sa.Column('avg_fat', sa.Float(), nullable=True, comment='平均脂肪摄入(g)'),
    sa.Column('avg_carbohydrate', sa.Float(), nullable=True, comment='平均碳水化合物摄入(g)'),
    sa.Column('avg_sugar', sa.Float(), nullable=True, comment='平均糖摄入(g)'),
    sa.Column('avg_sodium', sa.Float(), nullable=True, comment='平均钠摄入(mg)'),
    sa.Column('avg_dietary_fiber', sa.Float(), nullable=True, comment='平均膳食纤维摄入(g)'),
    sa.Column('overall_nutrition_score', sa.Float(), nullable=True, comment='整体营养评分(0-100)'),
    sa.Column('balance_score', sa.Float(), nullable=True, comment='营养均衡评分(0-100)'),
    sa.Column('health_score', sa.Float(), nullable=True, comment='健康评分(0-100)'),
    sa.Column('high_risk_products', sa.Integer(), nullable=True, comment='高风险产品数量'),
    sa.Column('medium_risk_products', sa.Integer(), nullable=True, comment='中风险产品数量'),
    sa.Column('low_risk_products', sa.Integer(), nullable=True, comment='低风险产品数量'),
    sa.Column('risk_factors', sa.JSON(), nullable=True, comment='主要风险因素'),
    sa.Column('category_stats', sa.JSON(), nullable=True, comment='产品分类统计'),
    sa.Column('brand_stats', sa.JSON(), nullable=True, comment='品牌统计'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI生成的报告摘要'),
    sa.Column('health_recommendations', sa.JSON(), nullable=True, comment='健康建议列表'),
    sa.Column('dietary_suggestions', sa.JSON(), nullable=True, comment='饮食建议'),
    sa.Column('improvement_areas', sa.JSON(), nullable=True, comment='需要改进的方面'),
    sa.Column('nutrition_trends', sa.JSON(), nullable=True, comment='营养趋势数据'),
    sa.Column('score_trends', sa.JSON(), nullable=True, comment='评分趋势'),
    sa.Column('consumption_patterns', sa.JSON(), nullable=True, comment='消费模式分析'),
    sa.Column('previous_period_comparison', sa.JSON(), nullable=True, comment='与上期对比'),
    sa.Column('peer_comparison', sa.JSON(), nullable=True, comment='同龄人对比'),
    sa.Column('standard_comparison', sa.JSON(), nullable=True, comment='标准值对比'),
    sa.Column('report_file_path', sa.String(length=500), nullable=True, comment='报告文件路径'),
    sa.Column('report_file_url', sa.String(length=500), nullable=True, comment='报告文件URL'),
    sa.Column('chart_data', sa.JSON(), nullable=True, comment='图表数据'),
    sa.Column('generation_time', sa.Float(), nullable=True, comment='生成耗时(秒)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='查看次数'),
    sa.Column('is_shared', sa.Boolean(), nullable=True, comment='是否分享'),
    sa.Column('is_favorite', sa.Boolean(), nullable=True, comment='是否收藏'),
    sa.Column('user_notes', sa.Text(), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True, comment='最后查看时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
